export const browserCoreExamples = [
  "SiriClaw-Instruct browser status",
  "SiriClaw-Instruct browser start",
  "SiriClaw-Instruct browser stop",
  "SiriClaw-Instruct browser tabs",
  "SiriClaw-Instruct browser open https://example.com",
  "SiriClaw-Instruct browser focus abcd1234",
  "SiriClaw-Instruct browser close abcd1234",
  "SiriClaw-Instruct browser screenshot",
  "SiriClaw-Instruct browser screenshot --full-page",
  "SiriClaw-Instruct browser screenshot --ref 12",
  "SiriClaw-Instruct browser snapshot",
  "SiriClaw-Instruct browser snapshot --format aria --limit 200",
  "SiriClaw-Instruct browser snapshot --efficient",
  "SiriClaw-Instruct browser snapshot --labels",
];

export const browserActionExamples = [
  "SiriClaw-Instruct browser navigate https://example.com",
  "SiriClaw-Instruct browser resize 1280 720",
  "SiriClaw-Instruct browser click 12 --double",
  'SiriClaw-Instruct browser type 23 "hello" --submit',
  "SiriClaw-Instruct browser press Enter",
  "SiriClaw-Instruct browser hover 44",
  "SiriClaw-Instruct browser drag 10 11",
  "SiriClaw-Instruct browser select 9 OptionA OptionB",
  "SiriClaw-Instruct browser upload /tmp/SiriClaw-Instruct/uploads/file.pdf",
  'SiriClaw-Instruct browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "SiriClaw-Instruct browser dialog --accept",
  'SiriClaw-Instruct browser wait --text "Done"',
  "SiriClaw-Instruct browser evaluate --fn '(el) => el.textContent' --ref 7",
  "SiriClaw-Instruct browser console --level error",
  "SiriClaw-Instruct browser pdf",
];
