export const browserCoreExamples = [
  "SiriClawInstruct browser status",
  "SiriClawInstruct browser start",
  "SiriClawInstruct browser stop",
  "SiriClawInstruct browser tabs",
  "SiriClawInstruct browser open https://example.com",
  "SiriClawInstruct browser focus abcd1234",
  "SiriClawInstruct browser close abcd1234",
  "SiriClawInstruct browser screenshot",
  "SiriClawInstruct browser screenshot --full-page",
  "SiriClawInstruct browser screenshot --ref 12",
  "SiriClawInstruct browser snapshot",
  "SiriClawInstruct browser snapshot --format aria --limit 200",
  "SiriClawInstruct browser snapshot --efficient",
  "SiriClawInstruct browser snapshot --labels",
];

export const browserActionExamples = [
  "SiriClawInstruct browser navigate https://example.com",
  "SiriClawInstruct browser resize 1280 720",
  "SiriClawInstruct browser click 12 --double",
  'SiriClawInstruct browser type 23 "hello" --submit',
  "SiriClawInstruct browser press Enter",
  "SiriClawInstruct browser hover 44",
  "SiriClawInstruct browser drag 10 11",
  "SiriClawInstruct browser select 9 OptionA OptionB",
  "SiriClawInstruct browser upload /tmp/SiriClawInstruct/uploads/file.pdf",
  'SiriClawInstruct browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "SiriClawInstruct browser dialog --accept",
  'SiriClawInstruct browser wait --text "Done"',
  "SiriClawInstruct browser evaluate --fn '(el) => el.textContent' --ref 7",
  "SiriClawInstruct browser console --level error",
  "SiriClawInstruct browser pdf",
];

